/**
 * @typedef {import('../types/index').DataItem DataItem}
 */
/**
 * 中国各民族名称的罗马字母拼写法和代码
 * Names of nationalities of China in romanization with codes
 * @type {DataItem[]}
 */
export const data = [
  { name: '汉族', romanization: 'Han', code: 'HA', digitalCode: '01' },
  { name: '柯尔克孜族', romanization: 'Kirgiz', code: 'KG', digitalCode: '29' },
  { name: '蒙古族', romanization: 'Mongol', code: 'MG', digitalCode: '02' },
  { name: '土族', romanization: 'Tu', code: 'TU', digitalCode: '30' },
  { name: '回族', romanization: 'Hui', code: 'HU', digitalCode: '03' },
  { name: '达斡尔族', romanization: 'Daur', code: 'DU', digitalCode: '31' },
  {
    name: '藏族',
    romanization: 'Zang',
    code: 'ZA',
    romanizationInternational: 'Tibetan',
    digitalCode: '04'
  },
  { name: '仫佬族', romanization: 'Mulao', code: 'ML', digitalCode: '32' },
  { name: '维吾尔族', romanization: 'Uygur', code: 'UG', digitalCode: '05' },
  { name: '羌族', romanization: 'Qiang', code: 'QI', digitalCode: '33' },
  { name: '苗族', romanization: 'Miao', code: 'MH', digitalCode: '06' },
  { name: '布朗族', romanization: 'Blang', code: 'BL', digitalCode: '34' },
  { name: '彝族', romanization: 'Yi', code: 'YI', digitalCode: '07' },
  { name: '撒拉族', romanization: 'Salar', code: 'SL', digitalCode: '35' },
  { name: '壮族', romanization: 'Zhuang', code: 'ZH', digitalCode: '08' },
  { name: '毛南族', romanization: 'Maonan', code: 'MN', digitalCode: '36' },
  { name: '布依族', romanization: 'Buyei', code: 'BY', digitalCode: '09' },
  { name: '仡佬族', romanization: 'Gelao', code: 'GL', digitalCode: '37' },
  {
    name: '朝鲜族',
    romanization: 'Chosen',
    code: 'CS',
    romanizationInternational: 'Korean',
    digitalCode: '10'
  },
  { name: '锡伯族', romanization: 'Xibe', code: 'XB', digitalCode: '38' },
  { name: '满族', romanization: 'Man', code: 'MA', digitalCode: '11' },
  { name: '阿昌族', romanization: 'Achang', code: 'AC', digitalCode: '39' },
  { name: '侗族', romanization: 'Dong', code: 'DO', digitalCode: '12' },
  { name: '普米族', romanization: 'Pumi', code: 'PM', digitalCode: '40' },
  { name: '瑶族', romanization: 'Yao', code: 'YA', digitalCode: '13' },
  { name: '塔吉克族', romanization: 'Tajik', code: 'TA', digitalCode: '41' },
  { name: '白族', romanization: 'Bai', code: 'BA', digitalCode: '14' },
  { name: '怒族', romanization: 'Nu', code: 'NU', digitalCode: '42' },
  { name: '土家族', romanization: 'Tujia', code: 'TJ', digitalCode: '15' },
  { name: '乌孜别克族', romanization: 'Uzbek', code: 'UZ', digitalCode: '43' },
  { name: '哈尼族', romanization: 'Hani', code: 'HN', digitalCode: '16' },
  { name: '俄罗斯族', romanization: 'Russ', code: 'RS', digitalCode: '44' },
  { name: '哈萨克族', romanization: 'Kazak', code: 'KZ', digitalCode: '17' },
  { name: '鄂温克族', romanization: 'Ewenki', code: 'EW', digitalCode: '45' },
  { name: '傣族', romanization: 'Dai', code: 'DA', digitalCode: '18' },
  { name: '德昂族', romanization: 'Deang', code: 'DE', digitalCode: '46' },
  { name: '黎族', romanization: 'Li', code: 'LI', digitalCode: '19' },
  { name: '保安族', romanization: 'Bonan', code: 'BN', digitalCode: '47' },
  { name: '傈僳族', romanization: 'Lisu', code: 'LS', digitalCode: '20' },
  { name: '裕固族', romanization: 'Yugur', code: 'YG', digitalCode: '48' },
  { name: '佤族', romanization: 'Va', code: 'VA', digitalCode: '21' },
  { name: '京族', romanization: 'Gin', code: 'GI', digitalCode: '49' },
  { name: '畲族', romanization: 'She', code: 'SH', digitalCode: '22' },
  { name: '塔塔尔族', romanization: 'Tatar', code: 'TT', digitalCode: '50' },
  { name: '高山族', romanization: 'Gaoshan', code: 'GS', digitalCode: '23' },
  { name: '独龙族', romanization: 'Derung', code: 'DR', digitalCode: '51' },
  { name: '拉祜族', romanization: 'Lahu', code: 'LH', digitalCode: '24' },
  { name: '鄂伦春族', romanization: 'Oroqen', code: 'OR', digitalCode: '52' },
  { name: '水族', romanization: 'Sui', code: 'SU', digitalCode: '25' },
  { name: '赫哲族', romanization: 'Hezhen', code: 'HZ', digitalCode: '53' },
  { name: '东乡族', romanization: 'Dongxiang', code: 'DX', digitalCode: '26' },
  { name: '门巴族', romanization: 'Monba', code: 'MB', digitalCode: '54' },
  { name: '纳西族', romanization: 'Naxi', code: 'NX', digitalCode: '27' },
  { name: '珞巴族', romanization: 'Lhoba', code: 'LB', digitalCode: '55' },
  { name: '景颇族', romanization: 'Jingpo', code: 'JP', digitalCode: '28' },
  { name: '基诺族', romanization: 'Jino', code: 'JN', digitalCode: '56' }
];

/**
 * 中国各民族名称
 * Names of nationalities of China
 */
export const names = [
  '汉族',
  '柯尔克孜族',
  '蒙古族',
  '土族',
  '回族',
  '达斡尔族',
  '藏族',
  '仫佬族',
  '维吾尔族',
  '羌族',
  '苗族',
  '布朗族',
  '彝族',
  '撒拉族',
  '壮族',
  '毛南族',
  '布依族',
  '仡佬族',
  '朝鲜族',
  '锡伯族',
  '满族',
  '阿昌族',
  '侗族',
  '普米族',
  '瑶族',
  '塔吉克族',
  '白族',
  '怒族',
  '土家族',
  '乌孜别克族',
  '哈尼族',
  '俄罗斯族',
  '哈萨克族',
  '鄂温克族',
  '傣族',
  '德昂族',
  '黎族',
  '保安族',
  '傈僳族',
  '裕固族',
  '佤族',
  '京族',
  '畲族',
  '塔塔尔族',
  '高山族',
  '独龙族',
  '拉祜族',
  '鄂伦春族',
  '水族',
  '赫哲族',
  '东乡族',
  '门巴族',
  '纳西族',
  '珞巴族',
  '景颇族',
  '基诺族'
];
